ALTER TABLE evt_places
    DROP COLUMN available;

ALTER TABLE evt_places
    ADD COLUMN used    BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN present BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;